import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const greetBurger = localFont({
  src: "../public/media/Bolle Burger/Greet Burger.otf",
  variable: "--font-greet-burger",
});

const sink = localFont({
  src: "../public/media/Bolle Burger/Sink.otf",
  variable: "--font-sink",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${greetBurger.variable} ${sink.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
